### PR TITLE
Fixed unity crash when reading BLE data

### LINKED ISSUE #5: Reading data from device never returns in unity
### Expected behaviour

The data comes back from device at a high frequency

### Actual behaviour

Unity hangs forever, seems like reading data never returns

### Steps to Reproduce

Run the program or start from UI toattempt to read data from genereic data attribute on connectionless BLE device

### Screenshots or Logs

_N/A_

### Additional Context

_N/A_

### PR DESCRIPTION
**Pull request by Fulons**
## Description

Fixed BLE read data method that was never returning when running in Unity. Created a coroutine in C++ that constantly retrieves and stores characteristic values. This data can then be polled on request using a separate method. C# test project updated to reflect the changes.

Closes #5 

## Checklist for Author

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have tested/added tests to validate my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Checklist for Reviewers

- [ ] Code follows the project style guidelines
- [ ] Code is self-documenting and well-commented
- [ ] All tests pass locally and on CI
- [ ] Related issue is referenced and closed as appropriate
- [ ] Documentation has been updated if necessary
- [ ] Changes are justified and necessary
- [ ] Code changes are covered by tests
- [ ] No new security vulnerabilities are introduced

## Additional Notes

Please add any additional notes for the reviewers here.

### CODE REVIEW

File: BleWinrtDll/BleWinrtDll.cpp [hunk 1]
```diff
@@ -4,6 +4,7 @@
 #include "stdafx.h"
 
 #include "BleWinrtDll.h"
+//#include <coroutine>
```
Comment (SamHignett) [inline BleWinrtDll/BleWinrtDll.cpp:7]: Commented code. Do we need this include? If not then remove the line.

File: BleWinrtDll/BleWinrtDll.cpp [hunk 2]
```diff
@@ -105,7 +105,7 @@ void saveError(const wchar_t* message, ...) {
 	va_start(args, message);
 	vswprintf_s(last_error, message, args);
 	va_end(args);
-	wcout << last_error << endl;
+	//wcout << last_error << endl;
```
Comment (SamHignett) [inline BleWinrtDll/BleWinrtDll.cpp:108]: Commented code. Do we still want/need this? If not then remove it.

File: BleWinrtDll/BleWinrtDll.cpp [hunk 3]
```diff
@@ -561,60 +559,201 @@ bool SendData(BLEData* data, bool block) {
 	return result;
 }
 
-fire_and_forget ReadDataAsync(BLECharacteristic* id, BLEData* data, condition_variable* signal, bool* result) {
+//Internal class for handling a coroutine constantly Reading data from characteristic
+//Thread safe?
+class Reading {
```
Comment (SamHignett) [inline BleWinrtDll/BleWinrtDll.cpp:564]: Does this class need to be in `BleWinrtDll.cpp`? Or can it be moved to a separate file to keep the size of this script low?

File: BleWinrtDll/BleWinrtDll.cpp [hunk 4]
```diff
@@ -561,60 +559,201 @@ bool SendData(BLEData* data, bool block) {
...
-				auto value = status.Value();
-				auto valueData = value.data();
-				uint32_t length = max(value.Length(), ARRAY_LENGTH(data->buf));
-				for (uint32_t i = 0; i < length; ++i) {
-					data->buf[i] = valueData[i];
+		//auto c = characteristic.CharacteristicProperties();
+		//if (((uint32_t)c & (uint32_t)GattCharacteristicProperties::Read) == 0) {
+		//	saveError(L"%s:%d Characteristic %s does not have read property!", __WFILE__, __LINE__, id->characteristicUuid);
+		//	co_return;
+		//}
```
Comment (SamHignett) [inline BleWinrtDll/BleWinrtDll.cpp:657]: Commented code. As it seems as though we have error handling for getting Characteristic Properties below, I'm assuming this is no longer needed? If not, then remove it.

File: BleWinrtDll/BleWinrtDll.cpp [hunk 5]
```diff
@@ -561,60 +559,201 @@ bool SendData(BLEData* data, bool block) {
...
+	}
+}
+
+void PollReadData(BLECharacteristic* id, uint8_t* data)
+{
+	lock_guard readingsGuard(readingsLock);
+	for (auto reading : readings)
+	{
+		if (*reading == *id) {
+			reading->getData(data, 512);
```
Comment (SamHignett) [inline BleWinrtDll/BleWinrtDll.cpp:736]: Magic number.  Replace with a member variable e.g. `bufferDataSize`

**Review by SamHignett — CHANGES_REQUESTED** [review]

File: BleWinrtDll/BleWinrtDll.cpp (hunk 3 above)
Comment (Fulons) [reply BleWinrtDll/BleWinrtDll.cpp:562]: I would suggest if we move this out we should also sepparate out a few more bits like helper functions etc.
It can be moved, however I've kept it all in one file to keep with the style of the cloned project (although braking it by using oop).

**Review by SamHignett — APPROVED** [review]
LGTM! 👍
